/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Laptop {
  'id' : bigint,
  'name' : string,
  'specs' : string,
  'category' : string,
  'brand' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addLaptop' : ActorMethod<
    [string, string, bigint, string, string],
    undefined
  >,
  'getAllLaptops' : ActorMethod<[], Array<Laptop>>,
  'getContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getLaptopsByBrand' : ActorMethod<[string], Array<Laptop>>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];