/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Laptop = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'specs' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLaptop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllLaptops' : IDL.Func([], [IDL.Vec(Laptop)], ['query']),
  'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getLaptopsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Laptop)], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Laptop = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'specs' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addLaptop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllLaptops' : IDL.Func([], [IDL.Vec(Laptop)], ['query']),
    'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getLaptopsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Laptop)], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };