/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'role' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const LaptopVariant = IDL.Record({
  'ram' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'storage' : IDL.Text,
  'variantName' : IDL.Text,
  'processor' : IDL.Text,
});
export const LaptopModel = IDL.Record({
  'imageUrls' : IDL.Vec(IDL.Text),
  'variants' : IDL.Vec(LaptopVariant),
  'modelName' : IDL.Text,
});
export const Brand = IDL.Record({
  'imageUrls' : IDL.Vec(IDL.Text),
  'brandName' : IDL.Text,
  'models' : IDL.Vec(LaptopModel),
});

export const idlService = IDL.Service({
  'converseWithAssistant' : IDL.Func([IDL.Text], [ChatMessage], []),
  'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getAllModels' : IDL.Func([IDL.Text], [IDL.Vec(LaptopModel)], ['query']),
  'getAllVariants' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(LaptopVariant)],
      ['query'],
    ),
  'getBrandByName' : IDL.Func([IDL.Text], [IDL.Opt(Brand)], ['query']),
  'getModelByName' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(LaptopModel)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({
    'role' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const LaptopVariant = IDL.Record({
    'ram' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'storage' : IDL.Text,
    'variantName' : IDL.Text,
    'processor' : IDL.Text,
  });
  const LaptopModel = IDL.Record({
    'imageUrls' : IDL.Vec(IDL.Text),
    'variants' : IDL.Vec(LaptopVariant),
    'modelName' : IDL.Text,
  });
  const Brand = IDL.Record({
    'imageUrls' : IDL.Vec(IDL.Text),
    'brandName' : IDL.Text,
    'models' : IDL.Vec(LaptopModel),
  });
  
  return IDL.Service({
    'converseWithAssistant' : IDL.Func([IDL.Text], [ChatMessage], []),
    'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getAllModels' : IDL.Func([IDL.Text], [IDL.Vec(LaptopModel)], ['query']),
    'getAllVariants' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(LaptopVariant)],
        ['query'],
      ),
    'getBrandByName' : IDL.Func([IDL.Text], [IDL.Opt(Brand)], ['query']),
    'getModelByName' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(LaptopModel)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };