/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Brand {
  'imageUrls' : Array<string>,
  'brandName' : string,
  'models' : Array<LaptopModel>,
}
export interface ChatMessage {
  'role' : string,
  'text' : string,
  'timestamp' : bigint,
}
export interface LaptopModel {
  'imageUrls' : Array<string>,
  'variants' : Array<LaptopVariant>,
  'modelName' : string,
}
export interface LaptopVariant {
  'ram' : string,
  'imageUrls' : Array<string>,
  'storage' : string,
  'variantName' : string,
  'processor' : string,
}
export interface _SERVICE {
  'converseWithAssistant' : ActorMethod<[string], ChatMessage>,
  'getAllBrands' : ActorMethod<[], Array<Brand>>,
  'getAllModels' : ActorMethod<[string], Array<LaptopModel>>,
  'getAllVariants' : ActorMethod<[string, string], Array<LaptopVariant>>,
  'getBrandByName' : ActorMethod<[string], [] | [Brand]>,
  'getModelByName' : ActorMethod<[string, string], [] | [LaptopModel]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];